# Game valid moves
GAME_VALID_MOVES = ('00', '01', '02', '10', '11', '12', '20', '21', '22')

# Game status codes
GAME_STATUS_INIT = 0
GAME_STATUS_HUMAN_MOVE_REQUIRED = 1
GAME_STATUS_COMP_MOVE_REQUIRED = 2
GAME_STATUS_OVER_DRAW = 3
GAME_STATUS_OVER_HUMAN_WINNER = 4
GAME_STATUS_OVER_COMP_WINNER = 5

# Game error codes
ERROR_CODE_GAME_ALREADY_ACTIVE = 0
ERROR_CODE_GAME_OVER = 1
ERROR_CODE_NOT_PLAYER_TURN = 2
ERROR_CODE_INVALID_MOVE = 3
